export const MOVIES__IS__LOAD = 'MOVIES__IS__LOAD';

export const GET__MOVIES__REQUESTED = 'GET__MOVIES__REQUESTED';
export const GET__MOVIES__SUCCESS = 'GET__MOVIES__SUCCESS';
export const GET__MOVIES__FAILURE = 'GET__MOVIES__FAILURE';

export const GET__MOVIE__REQUESTED = 'GET__MOVIE__REQUESTED';
export const GET__MOVIE__SUCCESS = 'GET__MOVIE__SUCCESS';
export const GET__MOVIE__FAILURE = 'GET__MOVIE__FAILURE';

export const SEARCH__BY__STRING = 'SEARCH__BY__STRING';
export const SEARCH_BY_TITLE = 'SEARCH_BY_TITLE';
export const SEARCH_BY_DIRECTOR = 'SEARCH_BY_DIRECTOR';
export const SEARCH_BY_RATING = 'SEARCH_BY_RATING';
export const SEARCH_BY_DATE = 'SEARCH_BY_DATE';
